name: Silverline
favicon: null
layout_spectrum: 0.50051
typography_spectrum: 0.74583
title: Cloud Solutions Firm based in NYC
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#050000'
    - '#70aec3'
    - '#9d0000'
    - '#b44f00'
  brandStrength: 0.25
  lightness: 0.3125
  saturation: 0.3125
  rhythmicContrast: 0.25
purpose: []
