name: Silverline
favicon: null
layout_spectrum: 0.7933470115531236
typography_spectrum: 0.9501731090713292
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.06578947394154966
  lightness: 0.15928704990074039
  saturation: 0.033189901150763035
  rhythmicContrast: 0.1377626706380397
purpose: []
